-- ============================================================
-- MIGRATION: Módulo Orçamentos (orcamento_modelos, orcamento_configuracoes, orcamentos)
-- Execute no Supabase SQL Editor (Dashboard > SQL Editor)
-- ============================================================

create table if not exists public.orcamento_modelos (
  id          uuid primary key default gen_random_uuid(),
  nome        text not null,
  ativo       boolean not null default true,
  created_by  uuid references auth.users(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.orcamento_configuracoes (
  id             uuid primary key default gen_random_uuid(),
  nome_empresa   text not null default 'Oliveira Joias',
  contato        text,
  endereco       text,
  whatsapp       text,
  instagram      text,
  texto_rodape   text,
  cor_principal  text not null default '#C9A84C',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists public.orcamentos (
  id                    uuid primary key default gen_random_uuid(),
  numero                integer generated by default as identity,
  cliente_nome          text,
  cliente_telefone      text,
  modelo_nome           text,
  material              text,
  largura               text,
  itens_inclusos        text[] not null default '{}',
  valor_vista           numeric(12,2) not null check (valor_vista > 0),
  percentual_acrescimo  numeric(5,2) not null,
  num_parcelas          integer not null,
  valor_parcelado       numeric(12,2) not null,
  valor_parcela         numeric(12,2) not null,
  prazo_fabricacao      text,
  observacoes           text,
  created_by            uuid references auth.users(id) on delete set null,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- Índices para as queries mais comuns
create index if not exists orcamentos_created_at_idx     on public.orcamentos (created_at);
create index if not exists orcamentos_numero_idx         on public.orcamentos (numero);
create index if not exists orcamento_modelos_ativo_idx   on public.orcamento_modelos (ativo);

-- Modelos de exemplo já cadastrados (conforme informado pelo usuário)
insert into public.orcamento_modelos (nome) values
  ('Tradicional 3mm'),
  ('Tradicional 4mm'),
  ('Reta 6mm'),
  ('Diamantada 5mm'),
  ('Abaulada 8mm');

-- ── RLS: orcamento_modelos ──────────────────────────────────────────────────
alter table public.orcamento_modelos enable row level security;

create policy "orcamento_modelos_select"
  on public.orcamento_modelos for select
  to authenticated
  using (true);

create policy "orcamento_modelos_insert"
  on public.orcamento_modelos for insert
  to authenticated
  with check (auth.uid() = created_by);

create policy "orcamento_modelos_update"
  on public.orcamento_modelos for update
  to authenticated
  using (true);

create policy "orcamento_modelos_delete"
  on public.orcamento_modelos for delete
  to authenticated
  using (true);

-- ── RLS: orcamento_configuracoes ────────────────────────────────────────────
alter table public.orcamento_configuracoes enable row level security;

create policy "orcamento_configuracoes_select"
  on public.orcamento_configuracoes for select
  to authenticated
  using (true);

create policy "orcamento_configuracoes_insert"
  on public.orcamento_configuracoes for insert
  to authenticated
  with check (true);

create policy "orcamento_configuracoes_update"
  on public.orcamento_configuracoes for update
  to authenticated
  using (true);

-- ── RLS: orcamentos ──────────────────────────────────────────────────────────
alter table public.orcamentos enable row level security;

create policy "orcamentos_select"
  on public.orcamentos for select
  to authenticated
  using (true);

create policy "orcamentos_insert"
  on public.orcamentos for insert
  to authenticated
  with check (auth.uid() = created_by);

create policy "orcamentos_update"
  on public.orcamentos for update
  to authenticated
  using (true);

create policy "orcamentos_delete"
  on public.orcamentos for delete
  to authenticated
  using (true);

-- ── GRANTs: sem isso o RLS acima nunca é avaliado, o Postgres barra antes ──
-- (retorna 42501 "permission denied for table X" mesmo com policy "using (true)")
grant select, insert, update, delete on public.orcamento_modelos to authenticated;
grant select, insert, update, delete on public.orcamento_configuracoes to authenticated;
grant select, insert, update, delete on public.orcamentos to authenticated;
